export  const cuisineList = [
    "African",
    "BBQ",
    "Breakfast",
    "Burgers",
    "Salads",
    "Biryani",
    "Wings",
    "Pasta",
    "Ethiopian",
    "Soup",
    "Indian",
    "Korean",
    "Sandwich",
    "Mexican",
    "Halal",
    "Nigerian",
    "Pasta",
    "Pizza",
    "Thai",
    "Seafood",
    "Spanish",
    "Fish & Chips",
    "Bakery",
    "Vegetarian",
    "Kids Friendly",
    "Pork chops",
];